name: Update Constants
run-name: Update Constants

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: find . -type f | grep -v '.git'

      - name: Replace Constants file
        run: rm -f docs/constants.md

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: List files
        run: find . -type f | grep -v '.git'
